### ISSUE TITLE
"Inner abort of servicelogger" with "unsafe call 'hasattr'"

### ISSUE THREAD

**Issue by aaaaalbert** [aaaaalbert/repy_v2#2]
Just a quick traceback dump concerning https://github.com/SensibilityTestbed/repy_v2/tree/add-sensorlock
```
1.97493004799 17 Internal Error
---
Uncaught exception!
---
Following is a full traceback, and a user traceback.
The user traceback excludes non-user modules. The most recent call is displayed last.

Full debugging traceback:
  "/data/data/com.sensibility_testbed/files/seattle/seattle_repy/repyV2/namespace.py", line 1438, in wrapped_function
  "/data/data/com.sensibility_testbed/files/seattle/seattle_repy/repyV2/repysensors.py", line 79, in refined_sensor_function_1d

User traceback:
  "/data/data/com.sensibility_testbed/files/seattle/seattle_repy/repyV2/repysensors.py", line 79, in refined_sensor_function_1d

Exception (with type 'exceptions.TypeError'): 'NoneType' object is not iterable
---
Inner abort of servicelogger
Unsafe call 'hasattr' with args '(<module 'posixpath' from '/data/data/com.sensibility_testbed/files/python/lib/python27.zip/posixpath.pyo'>, 'samefile')', kwargs '{}' <class 'exception_hierarchy.RunBuiltinException'>
Traceback (most recent call last):
  File "/data/data/com.sensibility_testbed/files/seattle/seattle_repy/repyV2/tracebackrepy.py", line 244, in handle_internalerror
  File "/data/data/com.sensibility_testbed/files/seattle/seattle_repy/repyV2/servicelogger.py", line 213, in multi_process_log
  File "/data/data/com.sensibility_testbed/files/seattle/seattle_repy/repyV2/servicelogger.py", line 119, in get_servicevessel
  File "/data/data/com.sensibility_testbed/files/seattle/seattle_repy/repyV2/persist.py", line 163, in restore_object
  File "/data/data/com.sensibility_testbed/files/seattle/seattle_repy/repyV2/persist.py", line 91, in _copy
  File "/home/lukas/.local/share/python-for-android/build/other_builds/python2/armeabi-v7a/python2/python-install/lib/python2.7/shutil.py", line 67, in copyfile
  File "/home/lukas/.local/share/python-for-android/build/other_builds/python2/armeabi-v7a/python2/python-install/lib/python2.7/shutil.py", line 55, in _samefile
  File "/data/data/com.sensibility_testbed/files/seattle/seattle_repy/repyV2/safe.py", line 506, in exceptionraiser
RunBuiltinException: Unsafe call 'hasattr' with args '(<module 'posixpath' from '/data/data/com.sensibility_testbed/files/python/lib/python27.zip/posixpath.pyo'>, 'samefile')', kwargs '{}'

```

**Comment by aaaaalbert** [comment]
The `TypeError` is raised in a helper function that wraps a call that is inserted into the Repy namespace in `namespace.py`.
